### ISSUE TITLE
Getting value of type 'String' has no member 'components'

### ISSUE THREAD

**Issue by noontideox** [swiftwasm/Tokamak#108]
Try to build with Swiftwasm in `wasm-DEVELOPMENT-SNAPSHOT-2020-04-07-a`.
Getting following error

`.build/checkouts/Runtime/Sources/Runtime/Metadata/TupleMetadata.swift:33:68: error: value of type 'String' has no member 'components'
        var labels = String(cString: pointer.pointee.labelsString).components(separatedBy: " ")`

**Comment by MaxDesiatov** [comment]
Hey @noontideox, thank you for trying it out! Tokamak support for WASI is still work in progress, I'm mainly testing it in Xcode, compiling it directly for macOS and running [`ReconcilerTests`](https://github.com/MaxDesiatov/Tokamak/blob/master/Tests/TokamakTests/ReconcilerTests.swift). 

The compilation error you've stumbled upon is a remnant of wickwirew/Runtime#67. It should be easily fixed upstream in `Runtime` by something like this:

```swift
#if !canImport(Foundation)
extension String {
  func components(separatedBy: String) -> [String] {
    // actual implementation here
  }
}
#endif
```

I just haven't got to it yet, as I'm also worried that this `Runtime` module doesn't have good support for absolute pointers described in swiftwasm/swift#20. To verify that, I'd like to run the test suite from `Runtime` on WASI first, which is currently blocked by swiftwasm/swift#597. I'm getting there slowly, I hope to get Foundation and XCTest more or less working in the next few days if all goes well. With working XCTest we could check that `Runtime` works well on WASI, or what exactly is broken otherwise.

**Comment by MaxDesiatov** [comment]
This is now resolved in the `main` branch.
